name: Coverage Check

on:
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and run tests with coverage
        run: mvn clean verify

      - name: Check JaCoCo Coverage
        run: |
          echo "Checking JaCoCo coverage..."
          COVERED=$(grep -oPm1 "(?<=<counter type=\"INSTRUCTION\">.*<covered>)[0-9]+" target/site/jacoco/jacoco.xml)
          MISSED=$(grep -oPm1 "(?<=<counter type=\"INSTRUCTION\">.*<missed>)[0-9]+" target/site/jacoco/jacoco.xml)
          TOTAL=$((COVERED + MISSED))
          RATIO=$(awk "BEGIN {print $COVERED/$TOTAL}")

          echo "Coverage ratio: $RATIO"
          MIN=0.80

          if (( $(echo "$RATIO < $MIN" | bc -l) )); then
            echo "❌ Coverage too low. Minimum required: $MIN"
            exit 1
          else
            echo "✅ Coverage is sufficient"
          fi
